#The Tether plugin allows players to attach a lead to any mob in Minecraft.

#Write mobs that you don't want leashable here.
blacklisted-mobs:
  - EXAMPLEMOB

#Messages
messages:
  prefix: "&8[&6&lTether&8] &r"
  reload: "Tether has been reloaded!"
  no-permission: "&cYou do not have permission!"